[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies"]

[dependencies]
forge-std = "1.9.7"
solady = "0.1.17"
"@openzeppelin-contracts" = "5.3.0"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
